In [2]:
import pandas as pd

df = pd.read_csv("C:\\Users\\DELL\\Downloads\\Python_Learning\\practice.csv")
df.columns = df.columns.str.strip()
df

   EmpID      Name Department  Age  Salary  Experience         City
0    101      Arun         IT   25   35000           2     Chennai
1    102    Priya         HR    29   42000           5     Madurai
2    103    Kumar         IT    32   58000           8     Chennai
3    104    Divya    Finance    27   39000           3  Coimbatore
4    105    Rahul         IT    24   30000           1       Salem
5    106    Meena         HR    35   62000          10     Chennai
6    107  Sathish    Finance    31   51000           7     Madurai
7    108     Nila         IT    28   47000           4  Coimbatore
8    109    Vijay      Sales    30   44000           6     Chennai
9    110    Kavya      Sales    26   36000           2       Salem

In [3]:
df.columns = df.columns.str.strip()
df["Department"] = df["Department"].str.strip()

In [4]:
df.head(5)  #1

   EmpID    Name Department  Age  Salary  Experience         City
0    101    Arun         IT   25   35000           2     Chennai
1    102  Priya          HR   29   42000           5     Madurai
2    103  Kumar          IT   32   58000           8     Chennai
3    104  Divya     Finance   27   39000           3  Coimbatore
4    105  Rahul          IT   24   30000           1       Salem

In [5]:
df.tail(3)   #1

   EmpID    Name Department  Age  Salary  Experience         City
7    108   Nila          IT   28   47000           4  Coimbatore
8    109  Vijay       Sales   30   44000           6     Chennai
9    110  Kavya       Sales   26   36000           2       Salem

In [6]:
df.to_csv("Test.cv" ,index = False)
df

   EmpID      Name Department  Age  Salary  Experience         City
0    101      Arun         IT   25   35000           2     Chennai
1    102    Priya          HR   29   42000           5     Madurai
2    103    Kumar          IT   32   58000           8     Chennai
3    104    Divya     Finance   27   39000           3  Coimbatore
4    105    Rahul          IT   24   30000           1       Salem
5    106    Meena          HR   35   62000          10     Chennai
6    107  Sathish     Finance   31   51000           7     Madurai
7    108     Nila          IT   28   47000           4  Coimbatore
8    109    Vijay       Sales   30   44000           6     Chennai
9    110    Kavya       Sales   26   36000           2       Salem

In [7]:
new_df = df[(df["Department"] == "IT") & (df["Salary"] > 40000)]    #2

new_df

   EmpID    Name Department  Age  Salary  Experience         City
2    103  Kumar          IT   32   58000           8     Chennai
7    108   Nila          IT   28   47000           4  Coimbatore

In [8]:
new_df = df.sort_values(by = "Salary")
new_df

   EmpID      Name Department  Age  Salary  Experience         City
4    105    Rahul          IT   24   30000           1       Salem
0    101      Arun         IT   25   35000           2     Chennai
9    110    Kavya       Sales   26   36000           2       Salem
3    104    Divya     Finance   27   39000           3  Coimbatore
1    102    Priya          HR   29   42000           5     Madurai
8    109    Vijay       Sales   30   44000           6     Chennai
7    108     Nila          IT   28   47000           4  Coimbatore
6    107  Sathish     Finance   31   51000           7     Madurai
2    103    Kumar          IT   32   58000           8     Chennai
5    106    Meena          HR   35   62000          10     Chennai

In [9]:
df.sort_values(by="Salary")    #3
df[["Name" ,"Department","Salary"]]

       Name Department  Salary
0      Arun         IT   35000
1    Priya          HR   42000
2    Kumar          IT   58000
3    Divya     Finance   39000
4    Rahul          IT   30000
5    Meena          HR   62000
6  Sathish     Finance   51000
7     Nila          IT   47000
8    Vijay       Sales   44000
9    Kavya       Sales   36000

In [10]:
print(df["Salary"].mean())       #4
print(df["Salary"].min())
print(df["Salary"].max())
print(df["Salary"].median())
print(df["Age"].mean())

44400.0
30000
62000
43000.0
28.7

In [11]:
df.groupby("Department")["Salary"]

In [12]:
df.groupby("Department")["Salary"].count()
df.groupby("Department")["Salary"].mean()
df.groupby("Department")["Salary"].max()

Department
Finance    51000
HR         62000
IT         58000
Sales      44000
Name: Salary, dtype: int64

In [13]:
df.groupby("Department")["Salary"].agg(["count", "mean", "max"]).sort_values(by="mean", ascending=False)

            count     mean    max
Department
HR              2  52000.0  62000
Finance         2  45000.0  51000
IT              4  42500.0  58000
Sales           2  40000.0  44000

In [14]:
df.groupby("Department")["Salary"].count()
df.groupby("Department")["Salary"].mean()
df.groupby("Department")["Salary"].max()

Department
Finance    51000
HR         62000
IT         58000
Sales      44000
Name: Salary, dtype: int64

In [15]:
df.groupby("Department")["Salary"].agg(["count","mean","max"]).sort_values("mean" ,ascending = False)    #5

            count     mean    max
Department
HR              2  52000.0  62000
Finance         2  45000.0  51000
IT              4  42500.0  58000
Sales           2  40000.0  44000

In [18]:
df["Annual Salary"] = df["Salary"]*12
df[["Name" ,"Salary" ,"Annual Salary"]]    #6

       Name  Salary  Annual Salary
0      Arun   35000         420000
1    Priya    42000         504000
2    Kumar    58000         696000
3    Divya    39000         468000
4    Rahul    30000         360000
5    Meena    62000         744000
6  Sathish    51000         612000
7     Nila    47000         564000
8    Vijay    44000         528000
9    Kavya    36000         432000

In [33]:
new_df = df.copy()
                                                 #7
new_df.loc[0, "City"] = None

new_df.isnull()

new_df.fillna("Unknown" ,inplace = True)

new_df.loc[len(new_df)] = new_df.loc[0]

new_df.drop_duplicates(inplace = True)

new_df

,EmpID,Name,Department,Age,Salary,Experience,City,Annual Salary,AnnualSalary
0,101,Arun,IT,25,35000,2,Unknown,420000,420000
1,102,Priya,HR,29,42000,5,Madurai,504000,504000
2,103,Kumar,IT,32,58000,8,Chennai,696000,696000
3,104,Divya,Finance,27,39000,3,Coimbatore,468000,468000
4,105,Rahul,IT,24,30000,1,Salem,360000,360000
5,106,Meena,HR,35,62000,10,Chennai,744000,744000
6,107,Sathish,Finance,31,51000,7,Madurai,612000,612000
7,108,Nila,IT,28,47000,4,Coimbatore,564000,564000
8,109,Vijay,Sales,30,44000,6,Chennai,528000,528000
9,110,Kavya,Sales,26,36000,2,Salem,432000,432000

In [ ]:
#df["SalaryLevel"]
#df["High"] = df["Salary"] >= 50000
#df["Medium"] = range(df["Salary"] 
#df["Low"] = df["Salary"] <40000
#df[["Name", "Salary" ,"SalaryLevel"]]

In [44]:
def salary_level(salary):
    if salary >= 50000:                   #8
        return "High"
    elif salary > 40000:
        return "Medium"
    else:
        return "Low"

df["SalaryLevel"] = df["Salary"].apply(salary_level)

print(df[["Name" ,"Salary" ,"SalaryLevel"]])

       Name  Salary SalaryLevel
0      Arun   35000         Low
1    Priya    42000      Medium
2    Kumar    58000        High
3    Divya    39000         Low
4    Rahul    30000         Low
5    Meena    62000        High
6  Sathish    51000        High
7     Nila    47000      Medium
8    Vijay    44000      Medium
9    Kavya    36000         Low

In [54]:
marks = pd.DataFrame({
    "EmpID" :[101,103,105,108,110],
    "TrainingScore" :[89,54,76,96,63]
})
                                                                #9
result = df.merge(marks,on = "EmpID" ,how = "left")

print(result[["EmpID" ,"Name" ,"TrainingScore"]])

   EmpID      Name  TrainingScore
0    101      Arun           89.0
1    102    Priya             NaN
2    103    Kumar            54.0
3    104    Divya             NaN
4    105    Rahul            76.0
5    106    Meena             NaN
6    107  Sathish             NaN
7    108     Nila            96.0
8    109    Vijay             NaN
9    110    Kavya            63.0

In [63]:
avg_salary = df.groupby("Department")["Salary"].mean()
print(avg_salary)
over_all = df["Salary"].mean()
print(over_all)

print(df[df["Salary"] > over_all][["Name" ,"Salary"]])

Department
Finance    45000.0
HR         52000.0
IT         42500.0
Sales      40000.0
Name: Salary, dtype: float64
44400.0
       Name  Salary
2    Kumar    58000
5    Meena    62000
6  Sathish    51000
7     Nila    47000

In [65]:
avg_salary =df.groupby("Department")["Salary"]

overall_avg = df["Salary"].mean()                  #10

print(df[df["Salary"] > overall_avg][["Name" ,"Salary"]])

       Name  Salary
2    Kumar    58000
5    Meena    62000
6  Sathish    51000
7     Nila    47000

In [ ]:
#10th my explanation

1) First I have grouped the salary by department and stored in  avg_salary.
2) To display the employees whose salary is above the overall average salary  we need to find overall_avg by finding the mean of Salary
3) If Salary  is greater than overall average it displays the employee name with their salary